name: windows-build-action

# 推送 Tag 时触发，Tag 必须以 v 开头 (例如 v1.0.0)
on:
  push:
    tags:
      - "v*"

jobs:
  # 这里只保留了 build-windows 这一个任务
  build-windows:
    runs-on: windows-latest
    permissions:
      contents: write
    steps:
      # 1. 签出代码 (强制拉取 master 分支最新代码)
      - uses: actions/checkout@v4
        with:
          ref: master
      
      # 2. 设置 Flutter 环境
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.38.x"
          cache: true
          
      # 3. 开启 Windows 桌面端支持
      - name: Enable Flutter Desktop
        run: flutter config --enable-windows-desktop
        
      # 4. 获取项目依赖
      - name: Restore Packages
        run: |
          cd simple_live_app
          flutter pub get
          
      # 5. 设置 flutter_distributor 环境
      - name: Install flutter_distributor
        run: dart pub global activate flutter_distributor
        
      # 6. 使用 Distributor 打包 Windows
      - name: Build Windows
        run: |
          cd simple_live_app
          flutter_distributor package --platform windows --targets msix,zip --skip-clean

      # 7. 上传 Windows 安装包至 Artifacts
      - name: Upload Windows APP to Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows
          path: |
            simple_live_app/build/dist/*/*.msix
            simple_live_app/build/dist/*/*.zip

      # 8. 读取本地 JSON 里的版本信息
      - name: Read version
        id: version
        uses: juliangruber/read-file-action@v1
        with:
          path: assets/app_version.json
          
      # 9. 打印版本信息到日志
      - name: Echo version
        run: echo "${{ fromJson(steps.version.outputs.content).version }}"
      - name: Echo version content
        run: echo "${{ fromJson(steps.version.outputs.content).version_desc }}"

      # 10. 自动发布到 GitHub Release
      - name: Upload Release
        uses: softprops/action-gh-release@v1
        with:
          name: "${{ fromJson(steps.version.outputs.content).version }}"
          body: "${{ fromJson(steps.version.outputs.content).version_desc }}"
          prerelease: ${{ fromJson(steps.version.outputs.content).prerelease }}
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            simple_live_app/build/dist/*/*.msix
            simple_live_app/build/dist/*/*.zip

      # 11. 结束提示
      - run: echo "🍏 Windows job's status is ${{ job.status }}."